### ISSUE TITLE
请问有使用说明吗？编译通不过，缺不少东西。

### ISSUE THREAD

**Issue by sharpwood** [QuantBox/QuantBoxXProvider#1]
![image](https://user-images.githubusercontent.com/7440304/34260816-1581761c-e6a2-11e7-8d5a-9a8773b9b40a.png)

**Comment by wjkhappy14** [comment]
?

**Comment by hthubert** [comment]
QauntBoxRohon.cs 直接删掉就行了，sfit_ctp_x64.dll 是 Ctp_C 的编译结果
